queue_rules:
  - name: default
    queue_conditions:
      - base=v0.34.x-celestia
      - label=S:automerge
    merge_conditions:
      - base=v0.34.x-celestia
      - label=S:automerge
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
